services:
  postgres:
    image: postgres:15-alpine
    container_name: booking_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  resource-service:
    build:
      context: .
      dockerfile: resource-service/Dockerfile
    container_name: booking_resource_service
    restart: always
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - postgres

volumes:
  postgres_data: